branches:
  only:
    - staging
cache: false
language: node_js
sudo: true
node_js:
- 6
before_install:
  - rvm install ruby-1.9.3-p551
env:
  global:
  - CF_API="https://api.fr.cloud.gov"
  - CF_USERNAME="gsa-18f-federalist_deployer"
  - CF_ORGANIZATION="gsa-18f-federalist"
  # CF_PASSWORD for gsa-18f-federalist_deployer user
  - secure: "E+PN3rztdIFrY02/0O3bAna0ClEeBe/IewLems9xnPtsZtBsobdGaA0RBoI5NRZlYElbF+x9CtfTyPCX5/iNEmBTHcz5I3n4DO6CSmPGVTU2RIZheSLhhLQ9dcOxZv+kArEWsN8WiIavZQQ14o2CgokAbZRewiDRjRtreACalA1cF6EgLiD9VEaZKwSihwCyey1QNoC8JNt/qAL/5YlV1ytgeiXCI2TNMyrnYvwJkeTkd9QzjNcJoD30FHZv63gPaEA3sKN7KXfx2Y2D56t4p+rnMnpcmpk/TMZcqNUc36v9A+JN6udsDW/LOD4vk+YztK026x93wMjW5sYuA/peAuJ5MbnCwaq3gIbvqQs7divLrQR/qWFw54OYaVaPdKJHeollRXHp/ZqnUNy0bvHEEaHBltXrkHSCyvr5KpumrTIokvouJDd+dqNjr2jaA4CO+Pl1QM+sqyIQvu6pIsOStRmGDtKFY2897jJ2VAk8HEsLo4wQZKUaAgPJ/yKXIjo+P0NiZnqwAaGF/TVxOJ5SqSMSHsAgulWRqguZVgdP5Zc2lxdyyTGUWQPDR7s0hJ5Byf0EAG45xVGUTzeTHZie1kRtlgfOmUrdur9KOP1RUFqop66mSQzeWPVtPP6Fp8TfwhNpiuDPCDbF+e6W6N5NxEbiuh7FOeNYVTZaavgRThA="
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.22.2"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - travis_retry cf install-plugin autopilot -f -r CF-Community
  - npm install
  - npm run build
deploy:
  - provider: script
    script: scripts/deploy-travis.sh
    skip_cleanup: true
    on:
      branch: staging
  - provider: script
    script: scripts/deploy-travis.sh
    skip_cleanup: true
    on:
      branch: master
